version: '3'

services:
  uplant-v3:
    image: uplant-v3:dev
    environment:
      - DOTNET_USE_POLLING_FILE_WATCHER=1
      - NUGET_PACKAGES=C:\.nuget\packages
      #- NUGET_FALLBACK_PACKAGES=$container_paths_to_fallback_packages_uplant-v3$
    volumes:
      - C:\Projetos\uplant-v3-api\uplant-v3:C:\app
      - C:\Users\Oshiro\onecoremsvsmon:C:\remote_debugger:ro
#$nuget_volume_mapping_uplant-v3$
    entrypoint: C:\\remote_debugger\\x64\\msvsmon.exe /noauth /anyuser /silent /nostatus /noclrwarn /nosecuritywarn /nofirewallwarn /nowowwarn /timeout:2147483646
    labels:
      com.microsoft.visualstudio.debuggee.program: "\"C:\\Program Files\\dotnet\\dotnet.exe\""
      #com.microsoft.visualstudio.debuggee.arguments: " $debuggee_arguments_probing_paths_uplant-v3$ bin\\Debug\\netcoreapp2.0\\uplantApi.dll"
      com.microsoft.visualstudio.debuggee.workingdirectory: "C:\\app"
      com.microsoft.visualstudio.debuggee.killprogram: "C:\\remote_debugger\\x64\\utils\\KillProcess.exe dotnet.exe"
